// <auto-generated />
namespace MyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CreateProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202510041214240_CreateProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
